### ISSUE TITLE
Not work with Nuxt's page

### ISSUE THREAD

**Issue by jdkcoder** [fluent-vue/fluent-vue#896]
### Describe the bug

Everytime I try to use fluent-vue with NuxtPage of Nuxt.js 3, I always got the warning `Could not find translation for key`. But when using only App.vue as the example of Nuxt.js 3 did, everything works normally: https://github.com/fluent-vue/examples/blob/main/nuxt-3/App.vue

### Reproduction

https://stackblitz.com/edit/github-amranf

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 662.30 MB / 15.84 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.29 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (128.0.2739.63)
  npmPackages:
    fluent-vue: latest => 3.6.0
    unplugin-fluent-vue: latest => 1.3.1
    vue: latest => 3.5.10
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/fluent-vue/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/fluent-vue/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Thank you for including a reproduction, this simplified debugging a lot.

`fluent-vue` cannot find translations because you are accessing them from `pages/index.vue` component. Translations for that component should be in `translations/{locale}/pages/index.vue.ftl`. Your example works after renaming `translations/{locale}/App.vue.ftl`  https://stackblitz.com/edit/github-amranf-32xfma?file=translations%2Fen%2Fpages%2Findex.vue.ftl

If you want to use global translations, you should add them to bundles in `plugins/fluent-vue.ts`.

**Comment by jdkcoder** [comment]
thank mate, I was too busying, I just re-remember that I posted this issue :)))
